export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR_VISIBLE = 'TOGGLE_SIDEBAR_VISIBLE'

export const TOGGLE_SIDEBAR_EXPANDABLE = 'TOGGLE_SIDEBAR_EXPANDABLE'

export const TOGGLE_SIDEBAR_POPUP = 'TOGGLE_SIDEBAR_POPUP'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const SET_USER = 'SET_USER'
